services:
  - type: web
    name: rahoot-app
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run start:production
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
    autoDeploy: true