services:
  - type: web
    name: rahoot-app
    env: node
    plan: free
    buildCommand: npm ci && npm run build
    startCommand: npm run all
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: WEBSOCKET_PUBLIC_URL
        fromService:
          type: web
          name: rahoot-app
          property: host
    autoDeploy: true